dashboard_stores_index:
    path: /list
    controller: App\Controller\Front\StoresController::listAction
    
dashboard_stores_details:
    path: /{slug}
    controller: App\Controller\Front\StoresController::showAction
    
  