api_accueil:
    path: /accueil
    controller: App\Controller\Api\IndexController::accueil

api_product_details:
    path: /product-details/{id}
    controller: App\Controller\Api\IndexController::productDetails

api_products_by_category:
    path: /products-by-category/{category}
    controller: App\Controller\Api\IndexController::productsByCategory
    
api_login:
    path: /api-for-mobile/login/{username}/{password}
    controller: App\Controller\Api\UserController::login